export const ROUTES = {
  HOME: '/',
  LOGIN: '/',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  NEW_ORDER: '/orders/new',
  ORDER_DETAIL: '/orders/:id',
  CLIENTS: '/clients',
  CLIENT_DETAIL: '/clients/:id',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  REPORTS: '/reports',
  ARCHIVE: '/archive',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  FAQ: '/faq',
  SUPPORT: '/support',
  PLANS: '/plans',
  TERMS: '/terms',
  PRIVACY: '/privacy'
};
