export const ROUTES = {
  HOME: '/',
  LOGIN: '/',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  NEW_PEDIDO: '/orders/new',
  DETAIL_PEDIDO: '/orders/:id',
  CLIENTES: '/clients',
  DETAIL_CLIENTE: '/clients/:id',
  PRODUCTOS: '/products',
  DETAIL_PRODUCTO: '/products/:id',
  REPORTES: '/reports',
  ARCHIVO: '/archive',
  PERFIL: '/profile',
  CONFIGURACION: '/settings',
  SOPORTE: '/support',
  PLANES: '/plans',
  TERMINOS: '/terms',
  PRIVACIDAD: '/privacy'
};
